version: "3.3"
services: 
    # Nginx Service
    nginx:
        container_name: ngx
        build:
            context: ./nginx
            dockerfile: dockerfile
        restart: unless-stopped
        tty: true
        volumes: 
            - ../:/var/www
        links: 
            - php
        ports: 
            - 8080:80
        networks: 
            - laravel-json-server

    # PHP Service
    php:
        container_name: php_fpm
        build: 
            context: ./php
            dockerfile: dockerfile
        restart: unless-stopped
        tty: true
        volumes: 
            - ../:/var/www
        links: 
            - mysql
        networks: 
            - laravel-json-server
    
    # Node.js Service
    node:
        container_name: node
        build: 
            context: ./node
            dockerfile: dockerfile
        tty: true
        volumes: 
            - ../:/var/wwww
        networks: 
            - laravel-json-server
                

    # MySQL Service
    mysql:
        container_name: db
        image: mysql:5.7
        restart: unless-stopped
        tty: true
        volumes: 
            - ./mysql/volumes:/var/lib/mysql
        ports: 
            - 3366:3306
        environment: 
            - MYSQL_DATABASE=laravel-json
            - MYSQL_ROOT_PASSWORD=laravel
        networks: 
            - laravel-json-server

    # Redis Service
    redis:
        container_name: redis
        image: redis:latest
        restart: unless-stopped
        ports: 
            - 6379:6379
        networks: 
            - laravel-json-server

networks: 
    laravel-json-server:
        driver: bridge
